apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-darah
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: test-darah
  template:
    metadata:
      labels:
        deployment: test-darah
    spec:
      containers:
      - name: the-container
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        command: ["echo",
                  "abc"]
        ports:
        - containerPort: 8080
