apiVersion: batch/v1
kind: Job
metadata:
  name: darah-telegram
spec:
  ttlSecondsAfterFinished: 30
  template:
    # This is the pod template
    spec:
      containers:
      - name: darah-telegram
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        resources:
          requests:
            cpu: 250m
            memory: 0.5Gi
        command: ["python",
                  "test.py"]
      restartPolicy: Never
    # The pod template ends here
