apiVersion: batch/v1
kind: Job
metadata:
  name: test-darah
spec:
  ttlSecondsAfterFinished: 30
  template:
    # This is the pod template
    spec:
      containers:
      - name: test-darah
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        command: ["python",
                  "test.py"]
      restartPolicy: Never
    # The pod template ends here
