# This workflow will build a docker container, publish it to Google Container Registry, and deploy it to GKE when there is a push to the "main" branch.
#
# To configure this workflow:
#
# 1. Ensure that your repository contains the necessary configuration for your Google Kubernetes Engine cluster, including deployment.yml, kustomization.yml, service.yml, etc.
#
# 2. Create and configure a Workload Identity Provider for GitHub (https://github.com/google-github-actions/auth#setting-up-workload-identity-federation)
#
# 3. Change the values for the GAR_LOCATION, GKE_ZONE, GKE_CLUSTER, IMAGE, REPOSITORY and DEPLOYMENT_NAME environment variables (below).
#
# For more support on how to run the workflow, please visit https://github.com/google-github-actions/setup-gcloud/tree/master/example-workflows/gke-kustomize

name: Data Ingestion and Analytics deployment

on:
  schedule:
    - cron:  '0 6 * * *'

  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: us-central1 # TODO: update region of the Artifact Registry
  GKE_CLUSTER: cluster-1    # TODO: update to cluster name
  GKE_ZONE: us-central1   # TODO: update to cluster zone
  DEPLOYMENT_NAME: darah-telegram # TODO: update to deployment name
  REPOSITORY: samples # TODO: update to Artifact Registry docker repository
  IMAGE: darah-telegram
  

jobs:
  setup-deploy:
    name: Setup, Deploy
    runs-on: ubuntu-latest
    environment: dev

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
       credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    # Get the GKE credentials so we can deploy to the cluster
    - name: 'Set up GKE credentials'
      uses: 'google-github-actions/get-gke-credentials@v2'
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    - name: DATA INGEST
      run: |-
        # replacing the image name in the k8s template
        # wget https://github.com/mikefarah/yq/releases/download/v4.40.5/yq_linux_amd64.tar.gz -O - |tar xz && mv ${BINARY} /usr/bin/yq
        yq -i '.spec.template.spec.containers[0].command[1] = "data_ingest.py" |
        .metadata.name = "darah-telegram-data-ingest" |
        .spec.template.spec.containers[0].name= "darah-telegram-data-ingest"' 'deployment.yaml'

        yq -i '.spec.selector.deployment = "darah-telegram-data-ingest" |
        .metadata.name = "darah-telegram-data-ingest"' 'service.yaml'

        yq -i '.commonLabels.app = "darah-telegram-data-ingest" |
        .metadata.name = "darah-telegram-data-ingest"' 'kustomization.yaml'

        cat deployment.yaml
        ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA
        ./kustomize build . | kubectl apply -f -
        kubectl get services -o wide
        # kubectl rollout status job/$darah-telegram-data-ingest
        sleep 10
        # kubectl get services -o wide
        kubectl wait --for=condition=complete --timeout=35m job/darah-telegram-data-ingest

    - name: DATA ANALYTICS
      run: |-
        # replacing the image name in the k8s template
        # wget https://github.com/mikefarah/yq/releases/download/v4.40.5/yq_linux_amd64.tar.gz -O - |tar xz && mv ${BINARY} /usr/bin/yq
        yq -i '.spec.template.spec.containers[0].command[1] = "data_analytics.py" |
        .metadata.name = "darah-telegram-data-analytics" |
        .spec.template.spec.containers[0].name= "darah-telegram-data-analytics"' 'deployment.yaml'

        yq -i '.spec.selector.deployment = "darah-telegram-data-analytics" |
        .metadata.name = "darah-telegram-data-analytics"' 'service.yaml'

        yq -i '.commonLabels.app = "darah-telegram-data-analytics" |
        .metadata.name = "darah-telegram-data-analytics"' 'kustomization.yaml'

        cat deployment.yaml
        ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA
        ./kustomize build . | kubectl apply -f -
        kubectl get services -o wide
        # kubectl rollout status job/$darah-telegram-data-analytics
        sleep 10
        # kubectl get services -o wide
        kubectl wait --for=condition=complete --timeout=35m job/darah-telegram-data-analytics
  