# This workflow will build a docker container, publish it to Google Container Registry, and deploy it to GKE when there is a push to the "main" branch.
#
# To configure this workflow:
#
# 1. Ensure that your repository contains the necessary configuration for your Google Kubernetes Engine cluster, including deployment.yml, kustomization.yml, service.yml, etc.
#
# 2. Create and configure a Workload Identity Provider for GitHub (https://github.com/google-github-actions/auth#setting-up-workload-identity-federation)
#
# 3. Change the values for the GAR_LOCATION, GKE_ZONE, GKE_CLUSTER, IMAGE, REPOSITORY and DEPLOYMENT_NAME environment variables (below).
#
# For more support on how to run the workflow, please visit https://github.com/google-github-actions/setup-gcloud/tree/master/example-workflows/gke-kustomize

name: DEV- Build and Deploy to GKE (MANUAL)

on: workflow_dispatch

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: us-central1 # TODO: update region of the Artifact Registry
  GKE_CLUSTER: cluster-1    # TODO: update to cluster name
  GKE_ZONE: us-central1   # TODO: update to cluster zone
  DEPLOYMENT_NAME: darah-telegram # TODO: update to deployment name
  REPOSITORY: samples # TODO: update to Artifact Registry docker repository
  IMAGE: darah-telegram
  

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: dev

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
       credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - run: |-
        gcloud --quiet auth configure-docker

    # Alternative option - authentication via credentials json
    # - id: 'auth'
    #   uses: 'google-github-actions/auth@v0'
    #   with:
    #     credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    # - name: Docker configuration
    #   run: |-
    #     echo ${{steps.auth.outputs.access_token}} | docker login -u oauth2accesstoken --password-stdin https://$GAR_LOCATION-docker.pkg.dev
    # Get the GKE credentials so we can deploy to the cluster
    - name: 'Set up GKE credentials'
      uses: 'google-github-actions/get-gke-credentials@v2'
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    # Build the Docker image
    - name: Build
      run: |-
        echo '${{ secrets.GCP_CREDENTIALS }}' >> creds.json
        echo '${{ secrets.TELEGRAM_TOKEN }}' >> token.txt
        echo '${{ secrets.TELEGRAM_CHANNEL_ID }}' >> channel.txt
        docker build \
          --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          --secret id=creds,src=creds.json \
          .
        docker tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" "gcr.io/$PROJECT_ID/$IMAGE:latest"
    # Push the Docker image to Google Artifact Registry
    - name: Publish
      run: |-
        docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"
    # Set up kustomize
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    - name: DATA INGEST
      run: |-
        # replacing the image name in the k8s template
        # wget https://github.com/mikefarah/yq/releases/download/v4.40.5/yq_linux_amd64.tar.gz -O - |tar xz && mv ${BINARY} /usr/bin/yq
        yq -i '.spec.template.spec.containers[0].command[1] = "data_ingest.py" |
        .metadata.name = "darah-telegram-data-ingest" |
        .spec.template.spec.containers[0].name= "darah-telegram-data-ingest"' 'deployment.yaml'

        yq -i '.spec.selector.deployment = "darah-telegram-data-ingest" |
        .metadata.name = "darah-telegram-data-ingest"' 'service.yaml'

        yq -i '.commonLabels.app = "darah-telegram-data-ingest" |
        .metadata.name = "darah-telegram-data-ingest"' 'kustomization.yaml'

        cat deployment.yaml
        ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA
        ./kustomize build . | kubectl apply -f -
        kubectl get services -o wide
        # kubectl rollout status job/$darah-telegram-data-ingest
        sleep 10
        # kubectl get services -o wide
        kubectl wait --for=condition=complete --timeout=5m job/darah-telegram-data-ingest

    - name: DATA ANALYTICS
      run: |-
        # replacing the image name in the k8s template
        # wget https://github.com/mikefarah/yq/releases/download/v4.40.5/yq_linux_amd64.tar.gz -O - |tar xz && mv ${BINARY} /usr/bin/yq
        yq -i '.spec.template.spec.containers[0].command[1] = "data_analytics.py" |
        .metadata.name = "darah-telegram-data-analytics" |
        .spec.template.spec.containers[0].name= "darah-telegram-data-analytics"' 'deployment.yaml'

        yq -i '.spec.selector.deployment = "darah-telegram-data-analytics" |
        .metadata.name = "darah-telegram-data-analytics"' 'service.yaml'

        yq -i '.commonLabels.app = "darah-telegram-data-analytics" |
        .metadata.name = "darah-telegram-data-analytics"' 'kustomization.yaml'

        cat deployment.yaml
        ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA
        ./kustomize build . | kubectl apply -f -
        kubectl get services -o wide
        # kubectl rollout status job/$darah-telegram-data-analytics
        sleep 10
        # kubectl get services -o wide
        kubectl wait --for=condition=complete --timeout=5m job/darah-telegram-data-analytics
   
    # Deploy the Docker image to the GKE cluster
    # - name: Set deploy_2 commands
    #   uses: mikefarah/yq@master
    #   with:
    #     cmd: yq -i '.spec.template.spec.containers[0].command |= ["python","test.py"] style="double"' 'deployment.yaml'
        
    # - name: Deploy_2
    #   run: |-
    #     # replacing the image name in the k8s template
    #     pwd
    #     ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA
    #     ./kustomize build . | kubectl apply -f -
    #     kubectl get services -o wide
    #     # kubectl rollout status job/$DEPLOYMENT_NAME
    #     sleep 10
    #     # kubectl get services -o wide
    #     kubectl wait --for=condition=complete --timeout=5m job/darah-telegram